service: airplanesCron

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 30
  versionFunctions: false
#  stage: dev
  region: us-east-1
  environment:
    # OPEN_SKY_USERNAME: "${self:custom.env.OPEN_SKY_USERNAME}"
    # OPEN_SKY_PASSWORD: ${file(./env.yml):${opt:stage}.OPEN_SKY_PASSWORD}
    # API_URL: ${file(./env.yml):${opt:stage}.API_URL}
    OPEN_SKY_USERNAME: "${self:custom.env.OPEN_SKY_USERNAME}"
    OPEN_SKY_PASSWORD: "${self:custom.env.OPEN_SKY_PASSWORD}"
    API_URL: "${self:custom.env.API_URL}"

package:
 exclude:
   - env.yml

functions:
  cron:
    handler: handler.cron
    events:
      - schedule: rate(5 minutes)

plugins:
  - serverless-offline-scheduler
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  env: ${file(env.yml):${self:custom.stage}}
