version: 0.2

env:
  variables:
    AWS_REGION: 'us-east-1'

phases:
  install:
    commands:
      - apt-get update
      - npm install -g serverless
      - npm install -g mocha
      - cd airplanes
      - npm install

  build:
    commands:
      - serverless deploy -s cicd -v
      - npm run lint
      - serverless invoke test -s cicd

  post_build:
    commands:
      - echo "yahoooo!"
