version: 0.2

env:
  variables:
    AWS_REGION: 'us-east-1'

phases:
  install:
    commands:
      - apt-get update
      - apt-get install jq
      - npm install -g serverless
      - npm install -g mocha
      - export OPEN_SKY_USERNAME=$(aws ssm get-parameters --names OPEN_SKY_USERNAME --with-decryption | jq '.Parameters | .[0] | .Value')
      - export OPEN_SKY_PASSWORD=$(aws ssm get-parameters --names OPEN_SKY_PASSWORD --with-decryption | jq '.Parameters | .[0] | .Value')
      - cd airplanes
      - npm install
      # - cd ../airplanesCron
      # - npm install

  build:
    commands:
      - cd ../airplanes
      - serverless deploy -s cicd -v
      - npm run lint
      - serverless invoke test -s cicd
      # - cd ../airplanesCron
      # - serverless deploy -s cicd -v
      # - npm run lint
      # - serverless invoke test -s cicd TODO

  post_build:
    commands:
      - echo "yahoo!"

artifacts:
  files:
    - serverless.yml
    - publish.zip
    - package.json
    - promotion.sh
  discard-paths: yes

