'use strict';

// tests for getAll
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
const _ = require('underscore');
let wrappedGetAll = mochaPlugin.getWrapper('getAll', '/handler.js', 'getAllAirplanes');
let wrappedPost = mochaPlugin.getWrapper('getAll', '/handler.js', 'postAirplane');



describe('getAll', () => {
  before(() => {
    const body = JSON.stringify({
      tailNumber: 'N97PD',
      latitude: 47.498,
      longitude: -122.218,
      ADSB: 'ad8295'
    });

    return wrappedPost.run({body: body})
    .then((response) => {
      console.log('Added airplane to db');
    });
  });

  it('should return 200', () => {
    return wrappedGetAll.run({}).then((response) => {
      expect(response.statusCode).to.equal(200);
    });
  });

  it('should return an airplane', () => {
    return wrappedGetAll.run({}).then((response) => {
      const parsedBody = JSON.parse(response.body);
      const found = _.findWhere(parsedBody, {tailNumber: 'N97PD'});
      expect(found).to.have.property('tailNumber');
      expect(found.tailNumber).to.equal('N97PD');
    });
  });
});
