'use strict';

// tests for post
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('post', '/handler.js', 'postAirplane');

describe('post', () => {
  it('should return 200', () => {
    const body = JSON.stringify({
      "tailNumber": "N435SP",
      "ADSB": "a5374f",
      "latitude": 47.498,
      "longitude": -122.218
    });

    return wrapped.run({body: body}).then((response) => {
      expect(response.statusCode).to.equal(200);
    });
  });
  it('should return the posted airplane', () => {
    const body = JSON.stringify({
      "tailNumber": "N5344K",
      "ADSB": "a6c237",
      "latitude": 47.498,
      "longitude": -122.218
    });
    return wrapped.run({body: body}).then((response) => {
      const parsedBody = JSON.parse(response.body);
      expect(parsedBody).to.have.property('tailNumber');
      expect(parsedBody.tailNumber).to.equal('N5344K');
    });
  });
});
